kind: ConfigMap
apiVersion: v1
metadata:
  name: tectonic-config
  namespace: tectonic-system
data:
  clusterID: "5a69f613-009a-4a90-b20c-92e8d80608c1"
  clusterName: "vagrant"
  installerPlatform: "sandbox-virtualbox-macos"
  certificatesStrategy: "installerGeneratedCA"
  tectonicUpdaterEnabled: "false"
  consoleBaseAddress: "https://console.tectonicsandbox.com"
  kubeAPIServerURL: "https://172.17.4.101:443"
  tectonicVersion: "1.7.1-tectonic.1"
  dexAPIHost: "tectonic-identity-api.tectonic-system.svc.cluster.local:5557"
