apiVersion: "etcd.coreos.com/v1beta1"
kind: "Cluster"
metadata:
  name: "kube-etcd"
  namespace: kube-system
spec:
  size: 1
  version: "3.1.8"
  pod:
    resources:
      requests:
        cpu: 500m
        memory: 300Mi
