apiVersion: monitoring.coreos.com/v1alpha1
kind: Prometheus
metadata:
  name: prometheus
  namespace: default
spec:
  replicas: 1
  version: v1.7.1
  serviceAccountName: prometheus
  serviceMonitorSelector:
    matchLabels:
      k8s-app: kube-state-metrics
  resources:
    requests:
      memory: 400Mi
  alerting:
    alertmanagers:
      - namespace: tectonic-system
        name: alertmanager-main
        port: web