apiVersion: monitoring.coreos.com/v1alpha1
kind: Prometheus
metadata:
  name: k8s
  namespace: tectonic-system
  labels:
    k8s-app: prometheus
    prometheus: k8s
spec:
  replicas: 1
  baseImage: quay.io/prometheus/prometheus
  version: v1.7.1
  externalUrl: https://console.tectonicsandbox.com/prometheus
  serviceAccountName: prometheus-k8s
  serviceMonitorSelector:
    matchExpressions:
    - {key: k8s-app, operator: Exists}
  ruleSelector:
    matchLabels:
      role: prometheus-rulefiles
      prometheus: k8s
  alerting:
    alertmanagers:
    - namespace: tectonic-system
      name: alertmanager-main
      port: web
  resources:
    limits:
      cpu: 400m
      memory: 2000Mi
    requests:
      cpu: 100m
      memory: 500Mi
