apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: prometheus-operator
  namespace: tectonic-system
  labels:
    k8s-app: prometheus-operator
    operator: prometheus
spec:
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: prometheus-operator
        operator: prometheus
    spec:
      serviceAccountName: prometheus-operator
      containers:
       - name: prometheus-operator
         image: quay.io/coreos/prometheus-operator:v0.11.0
         args:
         - "--kubelet-service=kube-system/kubelet"
         - "--config-reloader-image=quay.io/coreos/configmap-reload:v0.0.1"
         - "--prometheus-config-reloader=quay.io/coreos/prometheus-config-reloader:v0.0.2"
         ports:
         - name: http
           containerPort: 8080
         resources:
           requests:
             cpu: 100m
             memory: 50Mi
           limits:
             cpu: 200m
             memory: 300Mi
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
