apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: container-linux-update-operator
  namespace: tectonic-system
  labels:
    k8s-app: container-linux-update-operator
    managed-by-channel-operator: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: container-linux-update-operator
  template:
    metadata:
      labels:
        k8s-app: container-linux-update-operator
      name: container-linux-update-operator
    spec:
      containers:
      - name: update-operator
        image: quay.io/coreos/container-linux-update-operator:v0.2.2
        command:
        - "/bin/update-operator"
        - "--manage-agent=true"
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
